### ISSUE TITLE
Minimal files.

### ISSUE THREAD

**Issue by logi12345** [Akaronte/Azure-AD-Back-Client#1]
Hi, Hope you're alright mate. I

'm just wondering if I have my understanding correct In the frontend you have app.vue where there are calls to the login.ts file this is where API calls to the backend are handled in app.ts is that correct?

Thanks :)

**Comment by Akaronte** [comment]
All action is in backend, save data in backend and is not login send to login web. The frontend is only for id session and show the selected data of backend
